compute_environment: LOCAL_MACHINE
debug: true
distributed_type: NO
gpu_ids: "2"
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 1  # 修改为 1，表示只使用一个进程
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
